import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main >
        <div className=' bg-black h-screen px-[100px] text-white' >         
          <nav className='h-fit w-full pt-[80px] ' >
            <Image src={''} alt=' ' className='' />
            <div>
              <div className='group'>
                <button className='py-auto h-full px-4 group-hover:bg-button2 transition-all duration-300 '>Why Us &darr;</button>
                <div className='absolute left-0 p-10 bg-button2 w-full shadow-xxs transition-all duration-500 delay-300 border-b-1 border-primary hidden group-hover:flex '/>           
              </div> 
              <div className='group'>
                <button className='py-auto h-full px-4 group-hover:bg-button2 transition-all duration-300 '>Services and Solutions &darr;</button>
                <div className='absolute left-0 p-10 bg-button2 w-full shadow-xxs transition-all duration-500 delay-300 border-b-1 border-primary hidden group-hover:flex '/>           
              </div> 
              <div className='group'>
                <button className='py-auto h-full px-4 group-hover:bg-button2 transition-all duration-300 '>Programs and Offerings &darr;</button>
                <div className='absolute left-0 p-10 bg-button2 w-full shadow-xxs transition-all duration-500 delay-300 border-b-1 border-primary hidden group-hover:flex '/>           
              </div> 
            </div>
            <button className='px-6 py-4 rounded-xl bg-white text-black' >Sign in</button>
          </nav> 

          <div className='flex ' >
            <div>
              <p>We are your product engine, from Strategic Insights to Tactical Execution</p>
              <h2 className='text-[58px] ' >Being up-to-date is common; the competitive advantage is being up-to-tomorrow.</h2>
              <button className='px-6 py-4 w-[563px]' >Get Started</button>
            </div>
            <Image src={''} alt='' className='h-[485px] w-[433px]' />
          </div>
      
          <h2 className='text-center' >We work with</h2>

        </div>

        <div className='px-[100px] bg-black text-[#bebebe] ' >
          <div className=' h-[277px] bg-[#B0C4CD] '  >

          </div>
          <p className='View more' ></p>
          <h3>We’re a startup studio providing:</h3>
          <div className='flex flex-col' >
            <div className='flex gap-4' >
              <div>
                <div className='w-[102px] h-[102px] rounded-xl ' ></div>
                <h4>jkdsahekskjfj</h4>
              </div>
              <div>
                <div className='w-[102px] h-[102px] rounded-xl ' ></div>
                <h4>jkdsahekskjfj</h4>
              </div>
              <div>
                <div className='w-[102px] h-[102px] rounded-xl ' ></div>
                <h4>jkdsahekskjfj</h4>
              </div>
              <div>
                <div className='w-[102px] h-[102px] rounded-xl ' ></div>
                <h4>jkdsahekskjfj</h4>
              </div>
            </div>
            <div className='flex gap-4' >
              <div>
                <div className='w-[102px] h-[102px] rounded-xl ' ></div>
                <h4>jkdsahekskjfj</h4>
              </div>
              <div>
                <div className='w-[102px] h-[102px] rounded-xl ' ></div>
                <h4>jkdsahekskjfj</h4>
              </div>
              <div>
                <div className='w-[102px] h-[102px] rounded-xl ' ></div>
                <h4>jkdsahekskjfj</h4>
              </div>
              <div>
                <div className='w-[102px] h-[102px] rounded-xl ' ></div>
                <h4>jkdsahekskjfj</h4>
              </div>
            </div>
          </div>
          <div className='flex'>
            <Image src={''} alt='' width={'100%'} height={'100%'} className='h-[370px] h-[529px]'/>
            <div>
              <p>Against all odds: thoughts and observations from a permanent state of starting up. 
                We build your startup product from zero to one. We bring the tech and product expertise early-stage founders need.
                 We are your technical product team. We help get your startup from an idea into the market and beyond.
                  We typically work with pre-seed and seed-funded businesses alongside founders.</p>
            </div>
          </div>
        </div>




      </main>



      <footer >
      </footer>
    </div>
  )
}
